### ISSUE TITLE
Create Paths for Book Sections

### ISSUE THREAD

**Issue by daltonmcclain** [mita4829/Project3308#5]
Create adjacency matrix. Develop path creation algorithm.

**Comment by owattenmaker** [comment]
So I have an idea in my head for the algorithm I would use and want to know what you guys think. Originally I was going to do some brute force breadth first traversal but I think this algorithm is a little more efficient. 

Here are the steps:
1. From adjacency matrix find minimum distance path for the two nodes in question. It would then create an array of the minimum size and put the starting point in the first position. 
2. Start a breadth first traversal of the graph, however terminate that section as soon as the maximum distance has been reached. I think this would be a recursive function that would take 3 arguments: current node, where we are going, and current steps. Each step it puts the node into the array. This is removed if the path turns out to be a dead end. 
3. Once it finds the path it returns the array which then can be used to find all of the pictures we need. 

I think that each of the connections would have weights on them in order to help the efficiency of the algorithm. Common directions would be weighted differently. 

What do you guys think before I throw my head into a wall implementing this?

**Comment by mita4829** [comment]
For 1), the first adjacency matrix A, by default it's the matrix of one-step from one node to another node is the one we pre-write? And from there, we're just multiplying A by itself, A*A, until there exist a path from one node to another?

We have about 30 photos so we will have a 30x30 adjacency matrix. Matrix multiplication on A with A, is nxm \* nxm. First multiplying the first column of the adjacency matrix with the current matrix takes n*m operations. Multiplying the rest of the adjacency matrix will be n^2 \* m which is just O(cn^3) _double check my math, I might be wrong._ With our small number of photos, 30, every multiplication does 27,000 ops which will be practically unnoticeable to the user which is good as long as well keep the photo quantity low. 

[GraphTheoryAdjacency.pdf](https://github.com/mita4829/Project3308/files/145116/GraphTheoryAdjacency.pdf)

**Comment by owattenmaker** [comment]
That's what I was thinking, but what is the efficiency compared to a
regular search? Would well weighted nodes be more efficient? Which would
scale better. It is easy to do math for the matrix multiplication but I
don't know how it compares to the search.

**Comment by mita4829** [comment]
Go with the adjacency matrix but instead of multiplying all the rows, just multiple the row, _(starting point)_, until you're able to reach the end point. That way, the unnecessary multiplications doesn't slow thing down. Instead of n^3 doing so will be n^2 multiplication ops.

**Comment by owattenmaker** [comment]
So I just pushed the graph that I am going to use to the repository. If you want you can check it out and see if I have any mistakes. Under pathFinder.js in the dijkstra folder

**Comment by owattenmaker** [comment]
K well this is mostly done. Some stuff needs to be played with like how the graph gets created but hopefully it will be good for now.

**Comment by owattenmaker** [comment]
Closing this issue now. Some small improvements to be made but it works well enough.
